### ISSUE TITLE
Iron nuggets are turning into Steel nuggets instead of wrought iron

### ISSUE THREAD

**Issue by Masamato2906** [Ubus99/Schrecktech-Reborn#12]
**Describe the bug**
Iron nuggets are turning into Steel nuggets instead of wrought iron

**To Reproduce**
Put Iron nuggets into a Furnace

**Expected behavior**
Iron nuggets are converted to wrought Iron Nugget

**Additional context**
Just Removed Railcraft Steel Production

**Comment by Ubus99** [comment]
solved using crafttweaker, will be revorked using sourcecode later
